#include "dto/serialization.h"
#include <cstdio>
namespace placedb::dto {
namespace {
std::string Round(domain::Round v) { switch(v) { case domain::Round::kOnlineAssessment:return "online_assessment"; case domain::Round::kAptitude:return "aptitude"; case domain::Round::kCoding:return "coding"; case domain::Round::kTechnical:return "technical"; case domain::Round::kSystemDesign:return "system_design"; case domain::Round::kBehavioral:return "behavioral"; case domain::Round::kManagerial:return "managerial"; case domain::Round::kGroupDiscussion:return "group_discussion"; case domain::Round::kHr:return "hr"; case domain::Round::kOther:return "other"; } return "other"; }
std::string Outcome(domain::Outcome v) { switch(v) { case domain::Outcome::kOffered:return "offered"; case domain::Outcome::kRejected:return "rejected"; case domain::Outcome::kWithdrew:return "withdrew"; case domain::Outcome::kUnknown:return "unknown"; } return "unknown"; }
void Named(const std::optional<domain::NamedSlug>& v, std::string* out) { if (!v) { out->append("null"); return; } out->append("{\"slug\":").append(JsonString(v->slug_)).append(",\"name\":").append(JsonString(v->name_)).push_back('}'); }
void Author(const std::optional<domain::Author>& v, std::string* out) { if (!v) { out->append("null"); return; } out->append("{\"username\":").append(JsonString(v->username_)).append(",\"display_name\":").append(JsonString(v->display_name_)).push_back('}'); }
void QuestionBase(const domain::QuestionSummary& v, std::string* out) { out->append("\"public_id\":").append(JsonString(v.public_id_)).append(",\"slug\":").append(JsonString(v.slug_)).append(",\"title\":").append(JsonString(v.title_)).append(",\"company\":"); Named(v.company_,out); out->append(",\"role\":"); Named(v.role_,out); out->append(",\"round\":").append(v.round_?JsonString(Round(*v.round_)):"null").append(",\"source_year\":").append(v.source_year_?std::to_string(*v.source_year_):"null").append(",\"topics\":["); for(size_t i=0;i<v.topics_.size();++i){if(i)out->push_back(','); Named(v.topics_[i],out);} out->append("],\"difficulty\":{\"mean\":"); if(v.difficulty_.mean_) out->append(std::to_string(*v.difficulty_.mean_)); else out->append("null"); out->append(",\"vote_count\":").append(std::to_string(v.difficulty_.vote_count_)).append("},\"published_at\":").append(JsonString(v.published_at_)); }
void ExperienceBase(const domain::ExperienceSummary& v, std::string* out) { out->append("\"public_id\":").append(JsonString(v.public_id_)).append(",\"slug\":").append(JsonString(v.slug_)).append(",\"title\":").append(JsonString(v.title_)).append(",\"company\":"); Named(v.company_,out); out->append(",\"role\":"); Named(v.role_,out); out->append(",\"source_year\":").append(v.source_year_?std::to_string(*v.source_year_):"null").append(",\"outcome_visible\":").append(v.outcome_visible_?"true":"false"); if(v.outcome_visible_) out->append(",\"outcome\":").append(v.outcome_?JsonString(Outcome(*v.outcome_)):"null"); out->append(",\"author\":"); Author(v.author_,out); out->append(",\"published_at\":").append(JsonString(v.published_at_)); }
}
std::string JsonString(std::string_view raw) { std::string out="\""; for(const char raw_char:raw){const auto c=static_cast<unsigned char>(raw_char);switch(c){case '"':out+="\\\"";break;case '\\':out+="\\\\";break;case '\n':out+="\\n";break;case '\r':out+="\\r";break;case '\t':out+="\\t";break;default:if(c<32){char b[7];std::snprintf(b,sizeof b,"\\u%04x",c);out+=b;}else out.push_back(static_cast<char>(c));}} out+='"'; return out; }
std::string ToJson(const domain::QuestionSummary& v){std::string out="{";QuestionBase(v,&out);out+='}';return out;}
std::string ToJson(const domain::Question& v){std::string out="{";QuestionBase(v,&out);out.append(",\"prompt\":").append(JsonString(v.prompt_)).append(",\"answer_guidance\":").append(v.answer_guidance_?JsonString(*v.answer_guidance_):"null").append(",\"author\":"); Author(v.author_,&out);out+='}';return out;}
std::string ToJson(const domain::ExperienceSummary& v){std::string out="{";ExperienceBase(v,&out);out+='}';return out;}
std::string ToJson(const domain::Experience& v){std::string out="{";ExperienceBase(v,&out);out.append(",\"narrative\":").append(JsonString(v.narrative_)).append(",\"rounds\":[");for(size_t i=0;i<v.rounds_.size();++i){if(i)out+=',';const auto&r=v.rounds_[i];out.append("{\"ordinal\":").append(std::to_string(r.ordinal_)).append(",\"round\":").append(JsonString(Round(r.round_))).append(",\"notes\":").append(r.notes_?JsonString(*r.notes_):"null").append("}");}out+="]}";return out;}
}  // namespace placedb::dto
