#include "http/submission_contract.h"
#include "validation/unicode_text.h"
#include <algorithm>
#include <cctype>
#include <limits>
#include <set>
namespace placedb::http { namespace {
const std::set<std::string> rounds{"online_assessment","aptitude","coding","technical","system_design","behavioral","managerial","group_discussion","hr","other"};
const std::set<std::string> outcomes{"offered","rejected","withdrew","unknown"};
void Add(std::vector<FieldError>* e,std::string f,std::string c,std::string m){if(std::none_of(e->begin(),e->end(),[&](const auto& x){return x.field_id==f;}))e->push_back({std::move(f),std::move(c),std::move(m)});}
bool Only(const Json::Value& j,const std::set<std::string>& a){if(!j.isObject())return false;for(const auto& n:j.getMemberNames())if(!a.contains(n))return false;return true;}
size_t CodePoints(const std::string& value){const auto normalized=validation::NormalizeNfc(value);return normalized?normalized->code_points:std::numeric_limits<size_t>::max();}
std::string Required(const Json::Value& j,const char* n,size_t lo,size_t hi,std::vector<FieldError>* e){if(!j.isMember(n)||!j[n].isString()){Add(e,n,"REQUIRED","This field is required.");return{};}auto normalized=validation::NormalizeNfc(j[n].asString());if(!normalized){Add(e,n,"INVALID_UTF8","Use valid UTF-8 text.");return{};}if(normalized->code_points<lo||normalized->code_points>hi)Add(e,n,"LENGTH_OUT_OF_RANGE","The value has an invalid length.");return std::move(normalized->value);}
std::optional<std::string> Optional(const Json::Value& j,const char* n,std::vector<FieldError>* e){if(!j.isMember(n)||j[n].isNull())return{};if(!j[n].isString()){Add(e,n,"INVALID_TYPE","Use text or leave this field empty.");return{};}auto normalized=validation::NormalizeNfc(j[n].asString());if(!normalized){Add(e,n,"INVALID_UTF8","Use valid UTF-8 text.");return{};}return normalized->value.empty()?std::nullopt:std::optional<std::string>(std::move(normalized->value));}
std::optional<std::int16_t> Year(const Json::Value& j,std::int16_t max,std::vector<FieldError>* e){if(!j.isMember("source_year")||j["source_year"].isNull())return{};if(!j["source_year"].isInt()||j["source_year"].asInt()<2000||j["source_year"].asInt()>max){Add(e,"source_year","OUT_OF_RANGE","Use a year from 2000 through next year.");return{};}return static_cast<std::int16_t>(j["source_year"].asInt());}
}
QuestionSubmissionParse ParseQuestionSubmission(const Json::Value& j,std::int16_t max){QuestionSubmissionParse r;static const std::set<std::string>a{"title","prompt","answer_guidance","company_slug","job_role_slug","round","source_year","topic_slugs"};if(!Only(j,a)){Add(&r.errors,"form","UNKNOWN_FIELD","The request contains an unsupported field.");return r;}QuestionSubmission v;v.title=Required(j,"title",1,200,&r.errors);v.prompt=Required(j,"prompt",20,8000,&r.errors);v.answer_guidance=Optional(j,"answer_guidance",&r.errors);v.company_slug=Optional(j,"company_slug",&r.errors);v.job_role_slug=Optional(j,"job_role_slug",&r.errors);v.round=Optional(j,"round",&r.errors);v.source_year=Year(j,max,&r.errors);if(v.answer_guidance&&CodePoints(*v.answer_guidance)>8000)Add(&r.errors,"answer_guidance","TOO_LONG","Use no more than 8000 characters.");if(v.company_slug&&v.company_slug->size()>160)Add(&r.errors,"company_slug","TOO_LONG","Choose a listed company.");if(v.job_role_slug&&v.job_role_slug->size()>160)Add(&r.errors,"job_role_slug","TOO_LONG","Choose a listed role.");if(v.round&&!rounds.contains(*v.round))Add(&r.errors,"round","INVALID_VALUE","Choose a supported round.");if(j.isMember("topic_slugs")){if(!j["topic_slugs"].isArray()||j["topic_slugs"].size()>12)Add(&r.errors,"topic_slugs","OUT_OF_RANGE","Choose no more than 12 topics.");else{std::set<std::string>u;for(const auto&i:j["topic_slugs"]){if(!i.isString()||i.asString().empty()||i.asString().size()>160||!u.insert(i.asString()).second){Add(&r.errors,"topic_slugs","INVALID_VALUE","Choose unique listed topics.");break;}v.topic_slugs.push_back(i.asString());}}}if(r.errors.empty())r.value=std::move(v);return r;}
ExperienceSubmissionParse ParseExperienceSubmission(const Json::Value&j,std::int16_t max){ExperienceSubmissionParse r;static const std::set<std::string>a{"title","narrative","company_slug","job_role_slug","source_year","outcome_visible","outcome","anonymous","rounds"};if(!Only(j,a)){Add(&r.errors,"form","UNKNOWN_FIELD","The request contains an unsupported field.");return r;}ExperienceSubmission v;v.title=Required(j,"title",1,200,&r.errors);v.narrative=Required(j,"narrative",20,20000,&r.errors);v.company_slug=Optional(j,"company_slug",&r.errors);v.job_role_slug=Optional(j,"job_role_slug",&r.errors);v.source_year=Year(j,max,&r.errors);if(!j.isMember("outcome_visible")||!j["outcome_visible"].isBool())Add(&r.errors,"outcome_visible","REQUIRED","Choose whether to show the outcome.");else v.outcome_visible=j["outcome_visible"].asBool();if(j.isMember("anonymous")){if(!j["anonymous"].isBool())Add(&r.errors,"anonymous","INVALID_TYPE","Choose whether to show your name.");else v.anonymous=j["anonymous"].asBool();}v.outcome=Optional(j,"outcome",&r.errors);if(!v.outcome_visible&&j.isMember("outcome"))Add(&r.errors,"outcome","MUST_BE_OMITTED","Leave a hidden outcome out entirely.");if(v.outcome_visible&&!v.outcome)Add(&r.errors,"outcome","REQUIRED","Choose an outcome.");if(v.outcome&&!outcomes.contains(*v.outcome))Add(&r.errors,"outcome","INVALID_VALUE","Choose a supported outcome.");if(!j.isMember("rounds")||!j["rounds"].isArray()||j["rounds"].size()>20)Add(&r.errors,"rounds","OUT_OF_RANGE","Use no more than 20 rounds.");else for(const auto&i:j["rounds"]){if(!Only(i,{"round","notes"})||!i["round"].isString()||!rounds.contains(i["round"].asString())){Add(&r.errors,"rounds","INVALID_VALUE","Choose supported rounds.");break;}auto notes=Optional(i,"notes",&r.errors);if(notes&&CodePoints(*notes)>8000){Add(&r.errors,"rounds","TOO_LONG","Round notes are too long.");break;}v.rounds.push_back({i["round"].asString(),std::move(notes)});}if(r.errors.empty())r.value=std::move(v);return r;}
std::string DeriveSubmissionSlug(const std::string&t,const std::string&s){std::string out;bool sep=false;for(char raw:t){const auto c=static_cast<unsigned char>(raw);if(std::isalnum(c)){if(sep&&!out.empty())out.push_back('-');out.push_back(static_cast<char>(std::tolower(c)));sep=false;if(out.size()>=80)break;}else sep=true;}while(!out.empty()&&out.back()=='-')out.pop_back();if(out.empty())out="submission";out.push_back('-');out.append(s.substr(0,12));return out;}
}
